name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        VITE_REACT_APP_FIREBASE_API_KEY: ${{secrets.VITE_REACT_APP_FIREBASE_API_KEY}}
        VITE_REACT_APP_AUTH_DOMAIN: ${{secrets.VITE_REACT_APP_AUTH_DOMAIN}}
        VITE_REACT_APP_PROJECT_ID: ${{secrets.VITE_REACT_APP_PROJECT_ID}}
        VITE_REACT_APP_STORAGE_BUCKET: ${{secrets.VITE_REACT_APP_STORAGE_BUCKET}}
        VITE_REACT_APP_MESSAGING_SENDER_ID: ${{secrets.VITE_REACT_APP_MESSAGING_SENDER_ID}}
        VITE_REACT_APP_APP_ID: ${{secrets.VITE_REACT_APP_APP_ID}}
        VITE_REACT_APP_MEASUREMENT_ID: ${{secrets.VITE_REACT_APP_MEASUREMENT_ID}}
        VITE_FINGER_API_KEY: ${{secrets.VITE_FINGER_API_KEY}}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist